steps:
  dry-run:
    image: redpencil/plugin-docker-buildx
    settings:
      repo: ${CI_REPO_OWNER/redpencilio/redpencil}/virtuoso
      platforms: linux/amd64,linux/arm64
      dry_run: true
      purge: true
      ssh_key:
        from_secret: ssh_key
when:
  - event: manual
